### ISSUE TITLE
Do not disappear after the island is restarted

### ISSUE THREAD

**Issue by DeltaVetal26** [DevOnTheRocks/SkyClaims#39] opened 2017-06-22 10:30 UTC
### ===========
Core - spongeforge-1.10.2-2281-5.2.0-BETA-2353
SkyClaims-0.20.0-beta
Griefprevention-1.10.2-2.3.1.295
===========

**Comment by Mohron** [comment] 2017-06-22 12:25
_note to self: check https://github.com/DevOnTheRocks/SkyClaims/blob/development/src/main/java/net/mohron/skyclaims/world/RegenerateRegionTask.java#L57_

**Comment by DeltaVetal26** [comment] 2017-06-22 15:13
Unfortunately, the problem is not solved. The plug-in is the latest version. Disconnected all plug-ins, except private and islands - the problem did not disappear. Here's a video:
https://www.youtube.com/watch?v=B1GAgIDccYc&feature=youtu.be

**Comment by Mohron** [comment] 2017-06-22 15:28
@DeltaVetal26 I didn't claim to have fixed or done anything yet... I was just linking myself the code I need to check when I get home because it's obviously not working as intended.

**Comment by DeltaVetal26** [comment] 2017-06-22 15:51
I understand, I will wait for your answer :)

**Comment by Mohron** [comment] 2017-06-23 22:22
Fixed in 7cf5f865f0009242e920dd0107fe90f45ea2ef90

**Closed as completed by Mohron** 2017-06-23 22:22 UTC
