### ISSUE TITLE
Default schematic don't working.

### ISSUE THREAD

**Issue by yaroslav4167** [DevOnTheRocks/SkyClaims#111] opened 2019-06-18 18:59 UTC
### Version:

- **Sponge:** spongeforge-1.12.2-2838-7.1.7-RC3782
- **SkyClaims:** SkyClaims-0.27.2-S7.0-BETA
- **GriefPrevention:** griefprevention-1.12.2-4.3.0.689
- **Permissions:** LuckPerms-Sponge-4.4.26

### Expected Behavior:

`/is create` -> create default island.

### Actual Behavior:

`/is create` -> print list island schematics (with one element `default`)

### LuckPerms configs

default group:
Meta: 
 skyclaims.default-schematic = 'default'
Permissions:
 skyclaims.command.*
 skyclaims.arguments.biomes
 skyclaims.arguments.block
 skyclaims.arguments.schematics.default

**Comment by Mohron** [comment] 2019-06-19 11:57
Do you still have more than one schematic in your `config/skyclaims/schematic` folder? FYI, listing available schematics is the default behavior if you have more than 1 schematic.

**Comment by yaroslav4167** [comment] 2019-06-19 23:30
Yes. I have some schematics. but they are not available to this group. 
I thought that this would work if didn’t specify an additional parameter when `is create`.

**Comment by Mohron** [comment] 2019-06-20 00:00
The default schematic option came before the clickable list capability and there is a built-in default schematic which is why default schematic had to be ignored by default for the new feature to be on by default. A lot has changed in the upcoming release and this behavior has changed with it. I'll still need to make some changes before this particular behavior is where it needs to be though.

https://github.com/DevOnTheRocks/SkyClaims/releases/tag/beta-28-pr3

Nonetheless, the list schematic behavior was intended to override a default schematic when running the command in the version your running.

**Comment by yaroslav4167** [comment] 2019-06-20 11:03
In beta-28-pr3 all works correctly.
But, can i disable chest-gui interfaces in config? They feature conflicted with Quark (inventory sorting), and allows you to pick up items from this GUI.
![oX6E](https://user-images.githubusercontent.com/18057310/59844638-b33df580-935b-11e9-95e5-0ee58e9e4558.png)
![MQfu](https://user-images.githubusercontent.com/18057310/59844637-b2a55f00-935b-11e9-88ad-8e24468077eb.png)

**Comment by Mohron** [comment] 2019-06-20 11:06
Yes you can disable it in the config. That really sucks because you look like it could be a useful feature. Do all inventory menus break from quark that you know of?

**Comment by Mohron** [comment] 2019-06-20 11:11
The quark sorting seems to be a known issue. Looks like you'll need to disable one or the other.

https://github.com/SpongePowered/SpongeForge/issues/2289

**Comment by yaroslav4167** [comment] 2019-06-20 11:32
Yes. This bug works all plugins with chest-GUI interfaces.
Oh =/
Ok. Apparently have to disable one feature of Quark, for the sake of all such plugins.

**Comment by Mohron** [comment] 2019-06-28 01:53
Closing since the issue is fixed in the Pre-Release.

**Closed as completed by Mohron** 2019-06-28 01:53 UTC
Labels: enhancement
