### ISSUE TITLE
User's can delete what inside of Admin's claims

### ISSUE THREAD

**Issue by JoeSGT** [DevOnTheRocks/SkyClaims#88] opened 2018-02-06 03:59 UTC
### Version:

- **Sponge:** SpongeForge: 1.12.2-2586-7.1.0-BETA-2887
- **SkyClaims:** I had compile this https://github.com/DevOnTheRocks/SkyClaims/commit/68b6687a9495a77c9b1cc66cd67568217f9494d9
- **GriefPrevention:** 1.12.2-4.3.0.533
- **Permissions:** LuckPerms 4.0.124

### Expected Behavior:

When user's get inside of an admin claim they can use a clickable chat to delete admin claims
Reason why i have admin-claim is for my spawn point
### Actual Behavior:
There no errors outputting in console when this happens

### Steps To Reproduce:
1) have an user make a claim
2) setup an adminclaim
3) have the user do `/is delete` then go to the admin claim 
4) then on your chat you will see this https://gyazo.com/4b048079c98be34a8b139a87d6fd1859
not sure how to explain it in words then have the user click `[Yes]` in admin claim and boom they delete what inside of the admin claims in my case my user had to relog to see the effect that it really did delete what inside the admin claims this is not a ghost block it really did happen

**Comment by SubtypeZero** [comment] 2018-02-06 04:17
By default, an admin claim will be created for you within the island world in the region (0,0). If you put claims in other parts of the world that you have configured SkyClaims to use, those claims will be overwritten. Since your description didn't say anything about where the claim is or how close it is to islands, I'm assuming that you didn't read about this on the wiki, which you can see [here](https://devontherocks.github.io/SkyClaims/#/island-layout). If this is not the case, please give us some more details so we can better assist you.

**Comment by JoeSGT** [comment] 2018-02-06 04:26
Okay I read part's of the wiki not all I didn't read that, i wasn't aware of SkyClaims automatically creating an admin claim at 0,0 because i had used a downloadable spawn from planet minecraft for my spawn point and just set spawn there and use Admin claim there thinking that it would be fine that SkyClaims wasn't going to bug out like this. Does this mean that you cannot make AdminClaims because of this bug?

**Comment by SubtypeZero** [comment] 2018-02-06 04:28
To make this more clear, this is not a bug. SkyClaims assumes that everything outside of the region you have configured for your spawn to use will only be used for islands and not anything else. You can make the admin claim larger by specifying that you want more regions available for your spawn but you shouldn't change those settings if you already have islands created on your server.

"Anything built outside the designated spawn regions or player's islands may be cleared by SkyClaims' island generation routine."

**Comment by JoeSGT** [comment] 2018-02-06 05:16
it seem my spawn point is 0,0 cords and users still can use /is delete on it.
EDIT: i am not understanding the wiki it's not making it very clear about admin claim i had cleared out skyclaims config and GP since it's a new server tryin to make let it and then try to redo the step
i also did `/claimlist` and could not see if an admin claim is being made automatically by skyclaims

Also made a fresh test server it does NOT create an automatically admin claim from SkyClaims
and Updated SF to 1.12.2-2586-7.1.0-BETA-2889, LuckPerms-Sponge-4.0.126, griefprevention-1.12.2-4.3.0.533 still does NOT create an admin claim automatically and also switch to SkyClaims-0.27.0-S7.0-BETA still same issue, i dont understand why close this issue when clearly i am having issues

**Comment by JoeSGT** [comment] 2018-02-06 06:46
on here does not speak about any form of creating it's own AdminClaim 
https://devontherocks.github.io/SkyClaims/#/island-layout?id=island-placement

**Comment by JoeSGT** [comment] 2018-02-06 06:48
I see from this commit that it should auto create it https://github.com/DevOnTheRocks/SkyClaims/commit/47749dacbfe95a7ce6bcde4a4ec379042a1a28e2
but it does not i made a clear Clean Test server with no mods just LP,GP,SF,SkyClaims it does NOT auto create it 
This part that it said it auto create it, This information is not on the docs

**Comment by SubtypeZero** [comment] 2018-02-06 07:34
I haven't read through the whole commit, but it does say that an admin claim should be created with the first island, so what I'd do to try this out would be to try it on a fresh server, create an island, and then look for that admin claim. I would like to help more, but unfortunately I'm only human and need to get some sleep. I'm sure Mohron can clarify if I'm not back before he's on and we can definitely see about adding that to the wiki. I would do that now, but I'm not entirely sure how the process works at the moment and don't have the time to look at it right now. If you figure anything else out, just let us know here and we'll get back with you soon.

**Comment by Mohron** [comment] 2018-02-06 11:43
Spawn cannot be centered at 0,0 with only one spawn region because that is the  **lesser boundary** of region 0,0 (0,0-511,511). Claim type is not relevant if you manually create any claims inside a player's designated region as SkyClaims is designed to completely manage the Island lifecycle.

As Zero said, the admin claim isn't created until after the first island is created in order to give an admin a chance to change the config, if necessary. If said claim is not being created **after** the first island is created, that is a bug.  On the other hand, removal of any claim placed in an Island's region on reset or delete is not a bug.

**Comment by Mohron** [comment] 2018-02-06 12:18
Updated Docs: 9aca419f5f09d0235c8b825bcf34b90b7d7012cf

**Comment by JoeSGT** [comment] 2018-02-06 14:28
Ah got it,
going to write it here in case someone else has this issue they can read about how i got it working.
First on a fresh test server I did `/is create <name>` and it teleported me to my own island, then used a GriefPrevention command to find this admin claim `/claimlist` and click on `[Admin]` and Tp to the claim.
Thanks for updating and clarify the wiki. it was very confusing and misleading before.

**Closed as completed** 2018-02-06 14:30 UTC
Labels: question
