### ISSUE TITLE
Loot cleaning

### ISSUE THREAD

**Issue by DeltaVetal26** [DevOnTheRocks/SkyClaims#44] opened 2017-07-21 09:31 UTC
Good afternoon. And can you somehow do it so that when the island is restarted, the player's inventory is cleaned and the entire drop from the island is removed? Just dropped the drop from the chests.

**Comment by Mohron** [comment] 2017-07-21 14:24
Duplicate of #43

**Closed as completed by Mohron** 2017-07-21 14:24 UTC
Labels: duplicate
